name=Octopus Firmware
version=1.0.7
author=MIT Senseable City Lab
maintainer=oyinlola@mit.edu
sentence=Firmware library for Octopus integration using Arduino BLE Nano 33 rev2 or Nicla Vision.
paragraph=Octopus Platform is an open-source, low-cost environmental sensing tool.
category=Sensors
url=https://github.com/MIT-Senseable-City-Lab/octopus-firmware
architectures=mbed_nano, mbed_nicla
depends=ArduinoBLE, Adafruit DotStar, SD, Sensirion I2C SPS30, Arduino_HS300x, SparkFun u-blox GNSS Arduino Library
